"""add date column

Revision ID: 2e152e538980
Revises: b653b4aaf41d
Create Date: 2025-03-13 12:33:42.907448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e152e538980'
down_revision = 'b653b4aaf41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('date_time', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'date_time')
    # ### end Alembic commands ###
