"""remove date column

Revision ID: b653b4aaf41d
Revises: d462b90348ff
Create Date: 2025-03-13 12:29:40.321978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b653b4aaf41d'
down_revision = 'd462b90348ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('date_time', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
