"""added string column

Revision ID: d462b90348ff
Revises: a73214a56f02
Create Date: 2025-03-13 12:28:00.111142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd462b90348ff'
down_revision = 'a73214a56f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
